/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jgroups_again;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import org.jgroups.Message;

/**
 *
 * @author lezama
 */
public class PizarraProfesor extends javax.swing.JFrame {

    /**
     * Creates new form PizarraProfesor
     */
    private ChatRoom cr;
    private String strDibujo;
    
    public PizarraProfesor() {
        this.inicializaTodo();
    }

    PizarraProfesor(ChatRoom aThis) {
        this.cr = aThis;
        this.inicializaTodo();
    }
    
    private void inicializaTodo(){
        initComponents();
        panelPizarra1.setPP(this);
        
        lblTamano.setText("" + sldTamano.getValue());
        ArrayList<String> nombreColores = new ArrayList<>();
        HashMap<String, Color> listaColores = panelPizarra1.getListaColoresSelect();
        for(String a : listaColores.keySet()){
            //System.out.println("Add " + a);
            nombreColores.add(a);
        }
        panelPizarra1.setColor(listaColores.get(nombreColores.get(0))); // Inicia con el color preseleccionado
        panelPizarra1.setTamano(sldTamano.getValue());
        comColor.setModel(new DefaultComboBoxModel<>(nombreColores.toArray(new String[0])));
        
    }
    
    public PanelPizarra getPanelPizarra(){
        return panelPizarra1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        panelPizarra1 = new jgroups_again.PanelPizarra();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comColor = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sldTamano = new javax.swing.JSlider();
        jPanel6 = new javax.swing.JPanel();
        lblTamano = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar);

        javax.swing.GroupLayout panelPizarra1Layout = new javax.swing.GroupLayout(panelPizarra1);
        panelPizarra1.setLayout(panelPizarra1Layout);
        panelPizarra1Layout.setHorizontalGroup(
            panelPizarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        panelPizarra1Layout.setVerticalGroup(
            panelPizarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Color de trazo");
        jPanel4.add(jLabel1);

        comColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Azul", "Rojo", "Verde" }));
        comColor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comColorItemStateChanged(evt);
            }
        });
        jPanel4.add(comColor);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Tamaño del pincel");
        jPanel5.add(jLabel2);

        sldTamano.setMinimum(5);
        sldTamano.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldTamanoStateChanged(evt);
            }
        });
        jPanel5.add(sldTamano);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        lblTamano.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTamano.setText("1");
        jPanel6.add(lblTamano);

        jPanel5.add(jPanel6);

        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelPizarra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelPizarra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        panelPizarra1.limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void comColorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comColorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
          String item = (String) evt.getItem();
            // do something with object
            //System.out.println(item);
          HashMap<String, Color> listaColores = panelPizarra1.getListaColoresSelect();
          for(String col : listaColores.keySet()){
              if(item.equals(col)) panelPizarra1.setColor(listaColores.get(col));
          }
       }
    }//GEN-LAST:event_comColorItemStateChanged

    private void sldTamanoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldTamanoStateChanged
        //System.out.println("Tamano: " + sldTamano.getValue());
        panelPizarra1.setTamano(sldTamano.getValue());
        lblTamano.setText("" + sldTamano.getValue());
    }//GEN-LAST:event_sldTamanoStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        if(cr != null && cr.getModoUsuario() == ModoUsuario.PROFESOR){
            cr.cierraPizarras();
        }else {
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    public void sendStringDibujo(String puntosAString) {
        try {
            //System.out.println("Envio dibujo");
            Paquete p = new Paquete(TipoMensaje.DIBUJO, puntosAString);
            this.cr.getCanal().send(new Message(null, null, p));
            this.strDibujo = puntosAString;
        } catch (Exception ex) {
            //ex.printStackTrace();
            System.out.println("He fallado en retransmitir el dibujo");
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizarraProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizarraProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizarraProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizarraProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizarraProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> comColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblTamano;
    private jgroups_again.PanelPizarra panelPizarra1;
    private javax.swing.JSlider sldTamano;
    // End of variables declaration//GEN-END:variables

}
